version: 0.0.{build}

environment:
  BorogoveConnectionString:
    secure: K8/pTD62RotAYEX0tM/+ea4DmRV8zvkP2/Gl1TYot7Wgtl3nQNrIVCOOiIPuQ/4PHiHVsSIyNeWRytfCk5IVVsLXRF0eTG1JeoQO92q2UseHutXASsOArfIdZ3zAH8RxdXYYfaGIcEXGvA3rZL50YohG+ikhRNGRg3MktGU3IKrej3zl/UxNJy/e+8JAK2eQTdrbZ+rPtg2+ILy8P+WwEFqZFHJgTFg4qKakTJFqh5Uwzyuz5U7UU9OsanB5xzBme6ERT2IWuROEP/UwooHDQ+YG6Q42vGZkYy+lNWdNGfs=

install:
  - mkdir ..\Wyam
  - mkdir ..\Output
  - ps: Start-FileDownload "https://github.com/Wyamio/Wyam/releases/download/v0.11.2-beta/Wyam-v0.11.2-beta.zip" -FileName "..\Wyam\Wyam.zip"
  - 7z x ..\Wyam\Wyam.zip -o..\Wyam -r

build:
  publish_wap: true

before_build:
  - nuget restore

after_build:
  - ..\Wyam\Wyam.exe Borogove.TestSite --output ..\Output --verbose
  - dir Output

artifacts:
  - path: Output
    name: wyam output
    type: zip

deploy:
  - provider: WebDeploy
    server: https://BorogoveDevo.scm.azurewebsites.net/deploy
    website: BorogoveDevo
    username: commafun
    password:
        secure: uZ0JN3HNXcFOc+xgFgpKsA==
    remove_files: true
    app_offline: false