version: 0.0.{build}

environment:
  WebsiteRootUrl: https://borogovedevo.azurewebsites.net
  WebsiteLoginPage: login.html
  BorogoveConnectionString:
    secure: K8/pTD62RotAYEX0tM/+ea4DmRV8zvkP2/Gl1TYot7Wgtl3nQNrIVCOOiIPuQ/4PtGAusWf3tVv08KsBPTzQn1xluOVjCopoCazVI79bx3fhIm6/W23jMfTBeKodFaHuBVAxQjVaJzNZC/dSYU/GbPzHDJmcy9LK9lR2CejEB+qxi30je1T1l5nW6KGnUgQw+13v3gOLAwOTgS3NGGruSWmM1TBG2pmTXMe7CZTOrKKZV3d7NQM4qSQPUhK+Qx7DQODDrsrWaY/x9PlFR/1ki4KU4AqKdc5cMa90rK2j/jBqDp7ZiGmtV8fM48LPFepZ01zXRumkHgBQVdPBBLlP6w==
  Auth0ClientId: nJbojohqoR6aD5RaoyrY8K5AYFfUAT6l
  Auth0Domain: chimerror.auth0.com
  Auth0ClientSecret:
    secure: L+OFLeAaQrpEvHkS3/r7S59v4LmQH23gzFaIL4L3zxsjGF605RwN1mtLRnhRYqO59asbLbqDOkci464nahKcBoGIu3hRdHdA+vzbN7SZUXg=
  Auth0ManagementToken:
    secure: qjXx3IP0+XIS+aO6/+QY3tlR/0zxkxS/Mo5ZusItKiHClXCUALmVarlIXZvwPNMvuxKqj4s/FqYZtqPeAZnXHGfBI9aKdm76wfUtG9PiWaOa2wwl8iAnkrbJki95D37akEOMtVcDKDbxzLzinfk2axxqNIK4xgmOiZTP8GE2c6lDhiFRVkKKdPNk/rqZO9IdWswtaNzQqzKgpZ4DVcTsVAMoo4LuEb6YlBxBo/DX8/70d8BXZfLOYjvfRmxk1H+h7ssCdhvi2+f/f2/kBzRz+LLhzi5TIGf+PAlkCTHvSw/p/kuSVz4TSNez+zAxk7D4M/LI/jZXlq7FWYGJD/aOzTJSTJCoVeg6jQWajNhwJU8=

install:
  - mkdir ..\Wyam
  - mkdir ..\Output
  - ps: Start-FileDownload "https://github.com/Wyamio/Wyam/releases/download/v0.13.5-beta/Wyam-v0.13.5-beta.zip" -FileName "..\Wyam\Wyam.zip"
  - 7z x ..\Wyam\Wyam.zip -o..\Wyam -r

build:
  publish_wap: true

before_build:
  - nuget restore

after_build:
  - ..\Wyam\Wyam.exe Borogove.TestSite --output ..\Output --assembly C:\projects\borogove\Borogove\bin\Debug\** --verbose
  - dir Output

artifacts:
  - path: Output
    name: wyam output
    type: zip

deploy:
  - provider: WebDeploy
    server: https://borogovedevo.scm.azurewebsites.net:443/msdeploy.axd?site=BorogoveDevo
    website: BorogoveDevo
    username: $BorogoveDevo
    password:
      secure: NrYg8zLiW7Ex1ll0qVMorkj7+IcwQ1L7bYOXhTQR9KBJ2La9UUw5zyoU91R+hDh1NBpoMZYV5kv27KGGBuTsVA==
    remove_files: true
    app_offline: false
    ntlm: false
  - provider: FTP
    protocol: ftps
    host: waws-prod-bay-041.ftp.azurewebsites.windows.net
    username: BorogoveDevo\commafun
    password:
      secure: uZ0JN3HNXcFOc+xgFgpKsA==
    folder: site/wwwroot
    application: /Output/