install:
  - mkdir ..\Wyam
  - mkdir ..\Output
  # Fetch the latest version of Wyam
  - "curl -s https://raw.githubusercontent.com/Wyamio/Wyam/master/RELEASE -o ..\\Wyam\\wyamversion.txt"
  - set /P WYAMVERSION=< ..\Wyam\wyamversion.txt
  - echo %WYAMVERSION%
  # Get and unzip the latest version of Wyam
  - ps: Start-FileDownload "https://github.com/Wyamio/Wyam/releases/download/$env:WYAMVERSION/Wyam-$env:WYAMVERSION.zip" -FileName "..\Wyam\Wyam.zip"
  - 7z x ..\Wyam\Wyam.zip -o..\Wyam -r

before_build:
  - nuget restore

after_build:
  - ..\Wyam\Wyam.exe Borogove.TestSite --output ..\Output
  - dir %APPVEYOR_BUILD_FOLDER%\out

artifacts:
  - path: ..\Output
    name: wyam output
    type: zip
